# Generated by Django 3.1.3 on 2020-11-29 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Test',
        ),
    ]
