# Generated by Django 3.1.3 on 2020-11-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
